name: Test workflow dispatch from another workflow - source
on:
  release:
    types: ["prereleased"]

jobs:
  call_deploy_sandbox_workflow:
    if: startsWith(github.event.release.tag_name, "v2.")  
    runs-on: ubuntu-22.04
    steps:
      - name: Call test workflow test_gh_cli_2.yml
        run: gh workflow run gha_test_workflow_dispatch.yml -R gsnider2195/gha_digitalocean_test -f sandbox_environment=next.demo
        env:
          GH_TOKEN: ${{ secrets.GHA_DIGITALOCEAN_TEST_PAT }}
