name: Test workflow dispatch from another workflow - source
permissions:
  actions: write

on:
  workflow_dispatch:

jobs:
  call_deploy_sandbox_workflow:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Call test workflow test_gh_cli_2.yml
        run: gh workflow run test_gh_cli_2.yml -f sandbox_environment=next.demo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
